{
    'name': 'Bank Management',
    'version': '1.0',
    'summary': 'Bank Management System',
    'depends': ['base', 'mail', 'sale', 'stock',
                'planning', 'web', 'hr_expense','website','web_gantt','point_of_sale',],
    'data': ['security/ir.model.access.csv',
             'security/recycle_account_groups.xml',
             # 'security/recycle_account_record_rules.xml',

             'data/CusSeq.xml',
             'data/EmailTemplate.xml',
             'data/schedule_action.xml',
             # 'data/CustomerEmailTemplate.xml',
             'data/saleordermail.xml',
             'data/monthly_excel_report.xml',
             'wizard/demo.xml',
             'wizard/print.xml',
             'wizard/xlReport.xml',
             'reports/bank.template.xml',
             'reports/sale.commision-qweb.xml',
             'reports/customerPDF.xml',
             'views/customer.xml',
             'views/employee.xml',
             'views/account.xml',
             'views/loan.xml',
'views/menu_view.xml',
             'views/transaction1.xml',
             'views/query.xml',
             'views/sale_report.xml',
             'views/branch.xml',
             'views/kanbana.xml',
             'views/recycle.xml',
             'views/sale_order_commission_view.xml',
             'views/sale_line_oreder_commission.xml',
             'views/sale_inheritate_menu.xml',
             'views/practice.xml',
             'views/connection.xml',
             'views/configure.xml',
             'views/location.xml',
             'views/controllers_practice.xml',
             'views/form_user.xml',
             'views/public_users.xml',
             'views/private_user.xml',
             ],
    'assets': {
        'web.assets_backend': [
            'bank/static/src/view/js/planning_button.js',
            'bank/static/src/view/js/practice.js',
            'bank/static/src/view/js/expense_button.js',
            'bank/static/src/view/js/custome_module_button.js',
            # 'bank/static/src/view/js/custom_controller.js',
            'bank/static/src/view/js/control.js',
            'bank/static/src/view/js/icon.js',
            'bank/static/src/view/js/manifest.js',
            'bank/static/src/view/xml/temp.xml',
            'bank/static/src/view/xml/expense_button.xml',
            'bank/static/src/view/xml/dummy.xml',
            'bank/static/src/view/xml/custome_module_button.xml',
            # 'bank/static/src/view/xml/custom_controller.xml',
            'bank/static/src/view/xml/temp123.xml',

            'bank/static/src/view/xml/js_template.xml',


        ],
        'web.assets_frontend': [
            'bank/static/src/view/js/purchases_example.js',
            # 'bank/static/src/view/js/first.js',
            'bank/static/src/view/js/widget.js',
        ],

 'point_of_sale._assets_pos': [
            'bank/static/src/view/xml/pos.xml',
            'bank/static/src/view/xml/sundry_customer.xml',
     'bank/static/src/view/js/pos.js',
     'bank/static/src/view/js/sundry_customer.js',
     'bank/static/src/view/js/addnote.js',
     'bank/static/src/view/js/discount.js',


     # 'bank/static/src/view/js/custome_button.js',
     # 'bank/static/src/view/js/custome_button_popup.js',
     # 'bank/static/src/view/xml/custom_button.xml',
     # 'bank/static/src/view/xml/custom_button_popup.xml',


            'bank/static/src/app/location_button/location_button.js',
            'bank/static/src/app/location_button/location_button.xml',
            'bank/static/src/app/location_screen/location_screen.js',
            'bank/static/src/app/location_screen/location_screen.xml',


'bank/static/src/emi/button/button.js',
            'bank/static/src/emi/button/button.xml',
            'bank/static/src/emi/popup/popup.js',
            'bank/static/src/emi/popup/popup.xml',
 ],
    },

    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',

}
