{
    'name': 'Sale Approval',
    'version': '17.0.1.0.0',
    'category': 'sale',
    'depends': ['base', 'sale','sale_management'],
    'data': ['security/ir.model.access.csv',
             'security/res_user_group.xml',
             'views/sales_approval.xml',
             'reports/report_image.xml',
             ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'applicationf': False,
}
